//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercial
    {
        public int id { get; set; }
        public System.DateTime dataContato { get; set; }
        public int tipo { get; set; }
        public string Morada { get; set; }
        public string contacto { get; set; }
        public string Email { get; set; }
        public Nullable<int> telf { get; set; }
        public string Observ { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<bool> orcamentoEnviado { get; set; }
        public Nullable<int> estadoOrcamento { get; set; }
        public string Motivo { get; set; }
    
        public virtual estadoOrcamento estadoOrcamento1 { get; set; }
        public virtual estadoOrcamento estadoOrcamento2 { get; set; }
        public virtual tipoMorada tipoMorada { get; set; }
    }
}
