//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encomenda()
        {
            this.Producaos = new HashSet<Producao>();
            this.Producaos1 = new HashSet<Producao>();
            this.Recepcaos = new HashSet<Recepcao>();
            this.Recepcaos1 = new HashSet<Recepcao>();
            this.OrdemFabricoes = new HashSet<OrdemFabrico>();
            this.OrdemFabricoes1 = new HashSet<OrdemFabrico>();
            this.produto_new = new HashSet<produto_new>();
            this.produto_new1 = new HashSet<produto_new>();
        }
    
        public int id { get; set; }
        public string descricao_encomenda { get; set; }
        public string encomendaExterna { get; set; }
        public Nullable<System.DateTime> dataConclusao { get; set; }
        public Nullable<bool> concluido { get; set; }
        public string ficheiro_encomenda { get; set; }
        public System.DateTime dataEncomenda { get; set; }
        public Nullable<System.DateTime> dataPrevista { get; set; }
        public int quantidade { get; set; }
        public Nullable<int> controle_qualidade_producao { get; set; }
        public int encomenda_cliente { get; set; }
        public Nullable<int> encomenda_orcamento { get; set; }
        public Nullable<int> morada_cliente { get; set; }
        public int codigoProduto_id { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual produto produto1 { get; set; }
        public virtual tipoMorada tipoMorada { get; set; }
        public virtual orcamento orcamento { get; set; }
        public virtual tipoMorada tipoMorada1 { get; set; }
        public virtual orcamento orcamento1 { get; set; }
        public virtual morada morada { get; set; }
        public virtual morada morada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producao> Producaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producao> Producaos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcao> Recepcaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcao> Recepcaos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemFabrico> OrdemFabricoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemFabrico> OrdemFabricoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto_new> produto_new { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto_new> produto_new1 { get; set; }
    }
}
