//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formaco
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dataFormacao { get; set; }
        public Nullable<int> tipoOnJob_id { get; set; }
        public string nomeFormacao { get; set; }
        public Nullable<int> numHoras { get; set; }
    
        public virtual tipoFormacao tipoFormacao { get; set; }
    }
}
