//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionario()
        {
            this.Manutencoes = new HashSet<Manutenco>();
            this.Reports = new HashSet<Report>();
            this.orcamentoes = new HashSet<orcamento>();
        }
    
        public int id { get; set; }
        public string nome_user { get; set; }
        public string pass_user { get; set; }
        public int numero_user { get; set; }
        public Nullable<System.DateTime> data_entrada { get; set; }
        public Nullable<int> grupo_funcionario { get; set; }
        public Nullable<int> docs_funcionario { get; set; }
    
        public virtual docQualidade docQualidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manutenco> Manutencoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual listagemGrupo listagemGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orcamento> orcamentoes { get; set; }
    }
}
