//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtinFabricado
    {
        public int id { get; set; }
        public string loteProduzir { get; set; }
        public Nullable<int> encomenda_id { get; set; }
        public Nullable<long> gtinrecebido_id { get; set; }
        public Nullable<int> produto_id { get; set; }
        public Nullable<int> ordemFabrico_id { get; set; }
        public Nullable<int> qtdFabricada { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string gtinFabricado1 { get; set; }
    }
}
