//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manutenco
    {
        public int id { get; set; }
        public string manutencao { get; set; }
        public System.DateTime data_manutencao { get; set; }
        public int maquina { get; set; }
        public int nivel_manutencao { get; set; }
        public int funcinario { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual maquina maquina1 { get; set; }
        public virtual tipoManutencao tipoManutencao { get; set; }
    }
}
