//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maquina()
        {
            this.Manutencoes = new HashSet<Manutenco>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public int marca { get; set; }
        public string nserie { get; set; }
        public Nullable<System.DateTime> data_aquisicao { get; set; }
        public int ano_fabrico { get; set; }
        public string loja_id { get; set; }
        public string imagem { get; set; }
        public string ficheiro { get; set; }
        public Nullable<int> manutencao_id { get; set; }
    
        public virtual manutencao manutencao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manutenco> Manutencoes { get; set; }
        public virtual morada morada { get; set; }
    }
}
