//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class orcamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orcamento()
        {
            this.Encomendas = new HashSet<Encomenda>();
            this.Encomendas1 = new HashSet<Encomenda>();
        }
    
        public int id { get; set; }
        public Nullable<int> qtd_produto1 { get; set; }
        public Nullable<int> qtd_produto2 { get; set; }
        public Nullable<int> qtd_produto3 { get; set; }
        public Nullable<int> qtd_produto4 { get; set; }
        public Nullable<decimal> preco_produto1 { get; set; }
        public Nullable<decimal> preco_produto2 { get; set; }
        public Nullable<decimal> preco_produto3 { get; set; }
        public Nullable<decimal> preco_produto4 { get; set; }
        public string metrica_produto1 { get; set; }
        public string metrica_produto2 { get; set; }
        public string metrica_produto3 { get; set; }
        public string metrica_produto4 { get; set; }
        public Nullable<int> motivo { get; set; }
        public Nullable<System.DateTime> data_aprovacao { get; set; }
        public string ficheiro_orcamento { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<System.DateTime> data_recepcao { get; set; }
        public string observacoes { get; set; }
        public string loja_id { get; set; }
        public int moradas { get; set; }
        public string produto { get; set; }
        public int estado_orcamento { get; set; }
        public int user_alteracao { get; set; }
        public int morada_orcamento { get; set; }
    
        public virtual estadoOrcamento estadoOrcamento { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual morada morada { get; set; }
        public virtual motivoOrcamento motivoOrcamento { get; set; }
        public virtual tipoMorada tipoMorada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomendas1 { get; set; }
    }
}
