//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.Apuramentoes = new HashSet<Apuramento>();
            this.naoConformidadesOFs = new HashSet<naoConformidadesOF>();
            this.produto1 = new HashSet<produto>();
            this.Recepcaos = new HashSet<Recepcao>();
            this.Recepcaos1 = new HashSet<Recepcao>();
            this.Encomendas = new HashSet<Encomenda>();
            this.Encomendas1 = new HashSet<Encomenda>();
            this.OrdemFabricoes = new HashSet<OrdemFabrico>();
            this.OrdemFabricoes1 = new HashSet<OrdemFabrico>();
        }
    
        public int id { get; set; }
        public string codcomercial { get; set; }
        public string descricao { get; set; }
        public Nullable<long> ean13_produto { get; set; }
        public Nullable<long> dun_itf14_subemb { get; set; }
        public Nullable<long> itf_itf14_caixa { get; set; }
        public Nullable<decimal> comprimento { get; set; }
        public Nullable<decimal> largura { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string imagem { get; set; }
        public Nullable<long> NrCxsPlano { get; set; }
        public Nullable<long> NrPlanos { get; set; }
        public Nullable<long> NrUnidadesCx { get; set; }
        public Nullable<decimal> PesoPorCaixa { get; set; }
        public Nullable<long> NrCxsPalete { get; set; }
        public Nullable<long> UndsPorPalete { get; set; }
        public Nullable<decimal> CompPalete { get; set; }
        public Nullable<decimal> LargPalete { get; set; }
        public Nullable<decimal> AlturaPalete { get; set; }
        public Nullable<long> PesoPalete { get; set; }
        public Nullable<long> ImagemPalete { get; set; }
        public bool activo { get; set; }
        public Nullable<int> fichaProdutoElaborado_id { get; set; }
        public Nullable<System.DateTime> fichaProdutoDataElaboracao { get; set; }
        public Nullable<int> tipoproduto_id { get; set; }
        public Nullable<int> morada { get; set; }
        public Nullable<int> componente_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apuramento> Apuramentoes { get; set; }
        public virtual morada morada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<naoConformidadesOF> naoConformidadesOFs { get; set; }
        public virtual rastrealibidade rastrealibidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto> produto1 { get; set; }
        public virtual produto produto2 { get; set; }
        public virtual TipoProduto TipoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcao> Recepcaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcao> Recepcaos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomendas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemFabrico> OrdemFabricoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemFabrico> OrdemFabricoes1 { get; set; }
    }
}
