//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public Nullable<int> numero_report { get; set; }
        public string nome { get; set; }
        public System.DateTime data_report { get; set; }
        public Nullable<System.DateTime> data_provacao { get; set; }
        public Nullable<System.DateTime> data_resolucao { get; set; }
        public Nullable<int> user_report { get; set; }
    
        public virtual funcionario funcionario { get; set; }
    }
}
