//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class RH
    {
        public int id { get; set; }
        public int nrFuncionario { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> departamento_id { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public Nullable<int> custoHora { get; set; }
        public byte[] documentos { get; set; }
        public Nullable<int> diasFerias { get; set; }
        public string fardamentoNr { get; set; }
        public string sapatos { get; set; }
        public string calca { get; set; }
        public string polo { get; set; }
        public string casaco { get; set; }
        public string bata { get; set; }
        public System.DateTime dataAdmissao { get; set; }
        public string morada { get; set; }
        public Nullable<int> telefone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public Nullable<long> nif { get; set; }
        public byte[] docIdenfiticacao { get; set; }
        public byte[] fichaAptidao { get; set; }
        public byte[] curriculo { get; set; }
        public byte[] certHabilitacoes { get; set; }
        public byte[] registoCriminal { get; set; }
        public Nullable<bool> temporario { get; set; }
        public Nullable<int> numeroContrato { get; set; }
        public byte[] nss { get; set; }
        public System.DateTime dataInicioContrato { get; set; }
        public System.DateTime dataFimContrato { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual role role { get; set; }
    }
}
