//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class saidasEntrada
    {
        public int id { get; set; }
        public string gtinRef { get; set; }
        public string codcomercial { get; set; }
        public string descricao { get; set; }
        public Nullable<int> qtd { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string numGuiaExpedicao { get; set; }
        public string numGuiaRecepcao { get; set; }
    }
}
