//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro_2017
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiproEntities : DbContext
    {
        public SiproEntities()
            : base("name=SiproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apuramento> Apuramentoes { get; set; }
        public virtual DbSet<camposControlo> camposControloes { get; set; }
        public virtual DbSet<comercial> comercials { get; set; }
        public virtual DbSet<componenteComposto> componenteCompostoes { get; set; }
        public virtual DbSet<condicoesTemperatura> condicoesTemperaturas { get; set; }
        public virtual DbSet<ContaCorrenteStock> ContaCorrenteStocks { get; set; }
        public virtual DbSet<contato> contatoes { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<docQualidade> docQualidades { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<estadoOrcamento> estadoOrcamentoes { get; set; }
        public virtual DbSet<Formaco> Formacoes { get; set; }
        public virtual DbSet<funcionario> funcionarios { get; set; }
        public virtual DbSet<gestaoContrato> gestaoContratoes { get; set; }
        public virtual DbSet<listagemAcesso> listagemAcessoes { get; set; }
        public virtual DbSet<listagemGrupo> listagemGrupoes { get; set; }
        public virtual DbSet<manipulacao> manipulacaos { get; set; }
        public virtual DbSet<manutencao> manutencaos { get; set; }
        public virtual DbSet<Manutenco> Manutencoes { get; set; }
        public virtual DbSet<maquina> maquinas { get; set; }
        public virtual DbSet<morada> moradas { get; set; }
        public virtual DbSet<motivoNaoAaprovado> motivoNaoAaprovadoes { get; set; }
        public virtual DbSet<motivoOrcamento> motivoOrcamentoes { get; set; }
        public virtual DbSet<movimento> movimentoes { get; set; }
        public virtual DbSet<naoConformidadesOF> naoConformidadesOFs { get; set; }
        public virtual DbSet<Outsoucing> Outsoucings { get; set; }
        public virtual DbSet<permissao> permissaos { get; set; }
        public virtual DbSet<Producao> Producaos { get; set; }
        public virtual DbSet<rastrealibidade> rastrealibidades { get; set; }
        public virtual DbSet<Recepcao> Recepcaos { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RH> RHs { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<temporario> temporarios { get; set; }
        public virtual DbSet<tipoDocumento> tipoDocumentoes { get; set; }
        public virtual DbSet<tipoFormacao> tipoFormacaos { get; set; }
        public virtual DbSet<tipoManutencao> tipoManutencaos { get; set; }
        public virtual DbSet<tipoMorada> tipoMoradas { get; set; }
        public virtual DbSet<TipoNaoConformidade> TipoNaoConformidades { get; set; }
        public virtual DbSet<userGrupo> userGrupoes { get; set; }
        public virtual DbSet<verificacao> verificacaos { get; set; }
        public virtual DbSet<naoConforRecepcao> naoConforRecepcaos { get; set; }
        public virtual DbSet<orcamento> orcamentoes { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
        public virtual DbSet<TipoProduto> TipoProdutoes { get; set; }
        public virtual DbSet<FasesOrdemFabrico> FasesOrdemFabricoes { get; set; }
        public virtual DbSet<FimOperaco> FimOperacoes { get; set; }
        public virtual DbSet<MotivoFalta> MotivoFaltas { get; set; }
        public virtual DbSet<MotivoQuebra> MotivoQuebras { get; set; }
        public virtual DbSet<ParagemProducao> ParagemProducaos { get; set; }
        public virtual DbSet<naoConforExpedicao> naoConforExpedicaos { get; set; }
        public virtual DbSet<saidasEntrada> saidasEntradas { get; set; }
        public virtual DbSet<produtosExpedido> produtosExpedidos { get; set; }
        public virtual DbSet<gtinRecebido> gtinRecebidos { get; set; }
        public virtual DbSet<gtinFabricado> gtinFabricados { get; set; }
        public virtual DbSet<Encomenda> Encomendas { get; set; }
        public virtual DbSet<Expedicao> Expedicaos { get; set; }
        public virtual DbSet<OrdemFabrico> OrdemFabricoes { get; set; }
        public virtual DbSet<produto_new> produto_new { get; set; }
    }
}
